#!/usr/bin/env bash

set -e

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

main() {
  local subcommand="$1"

  cd "$root"
  [[ -d qa_reports ]] || mkdir qa_reports

  find . -name '*.pyc' -delete
  python -m compileall -x jinja2 -q ohmu

  if [[ "$1" ]]; then
    [[ -e env/bin/activate ]] || subcommand_install
    . env/bin/activate
    "subcommand_$subcommand"
  else
    subcommand_all
  fi
}

subcommand_all() {
  subcommand_install
  subcommand_lint
  subcommand_cover
}

subcommand_install() {
  [[ -d env ]] || virtualenv env
  . env/bin/activate
  pip install pip setuptools -U
  python setup.py install
  pip install \
      'coverage==3.7.1' \
      'flake8==2.4.1' \
      'green==1.11.0' \
      'nose==1.3.7' \
      'pudb==2015.3'
  python setup.py test
}

subcommand_clean() {
  rm -fr env ohmu.egg-info ./*.egg dist qa_reports
  find . -name '*.pyc' -delete
}


subcommand_lint() {
  local args=(
    --max-complexity 7
    --exclude=.ropeproject
  )
  flake8 "${args[@]}" ohmu > qa_reports/flake8 || true
  echo -n "$(tput setaf 1)"
  cat qa_reports/flake8
  echo -n "$(tput sgr0)"
}

subcommand_cover() {
  green ohmu/test_*.py -vv
  nosetests --with-coverage --cover-erase --cover-package=ohmu
  coverage -rm
  coverage xml -o qa_reports/coverage.xml
  rm -f .coverage
}

main "$@"
